{% set name = "openjdk" %}
{% set version = "8.0.252" %}
{% set zulu_build = "8.46.0.19-ca" %}
{% set build_number = 1004 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_x64.tar.gz  # [linux64]
    sha256: ab8a4194006f12dd48bf7f176ca7879706d3f8fc7d3208313a46cc9ee2270716  # [linux64]

  - url: https://cdn.azul.com/zulu-embedded/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_aarch64.tar.gz  # [aarch64]
    sha256: 504188a49b353ff9424d2ddedc73f9b827c435f6eb5518cd7d592afbb7468152  # [aarch64]

  - url: https://cdn.azul.com/zulu-embedded/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_ppc64.tar.gz  # [ppc64le]
    sha256: f697d6054483ece5c475d6bc3d23a16fd251521b7743be1c2e85648f8e0267e2  # [ppc64le]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-macosx_x64.zip  # [osx]
    sha256: c7ef75d36a1cf0a30c6ea3fdeadd780dd55cafeb120de6dce4a469f91e435cba  # [osx]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-win_x64.zip  # [win64]
    sha256: 993ef31276d18446ef8b0c249b40aa2dfcea221a5725d9466cbea1ba22686f6b  # [win64]

  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip  # [linux]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a  # [linux]
    folder: fonts  # [linux]

build:
  number: {{ build_number }}
  skip: true  # [win32 or linux32]

test:
  requires:
    - {{ compiler('c') }}  # [not win]
  files:
    - test-jni  # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh  # [not win]

about:
  home: https://www.azul.com/products/zulu/
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: The Zulu OpenJDK build.
  description: Zulu OpenJDK is an open source build of the Java JDK.

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - hadim
