{% set name = "openjdk" %}
{% set version = "11.0.9.1" %}
{% set zulu_build = "11.43.55-ca" %}
{% set zulu_build_arm64 = "11.43.1007-ca" %}
{% set openjdk_revision = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-{{ version }}+{{ openjdk_revision }}/OpenJDK11U-jdk_ppc64le_linux_hotspot_{{ version }}_{{ openjdk_revision }}.tar.gz   # [build_platform == "linux-ppc64le"]
    sha256: d94b6b46a14ab0974b1c1b89661741126d8cf8a0068b471b8f5fa286a71636b1  # [build_platform == "linux-ppc64le"]

  - url: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-{{ version }}+{{ openjdk_revision }}/OpenJDK11U-jdk_aarch64_linux_hotspot_{{ version }}_{{ openjdk_revision }}.tar.gz   # [build_platform == "linux-aarch64"]
    sha256: e9cea040cdf5d9b0a2986feaf87662e1aef68e876f4d66664cb2be36e26db412  # [build_platform == "linux-aarch64"]

  - url: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-{{ version }}+{{ openjdk_revision }}/OpenJDK11U-jdk_x64_linux_hotspot_{{ version }}_{{ openjdk_revision }}.tar.gz   # [build_platform == "linux-64"]
    sha256: e388fd7f3f2503856d0b04fde6e151cbaa91a1df3bcebf1deddfc3729d677ca3  # [build_platform == "linux-64"]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-macosx_x64.zip  # [osx and x86_64]
    sha256: 45a3d08a6ef21404975433bd8babe4e04c0dbfe8f6e5f34561d89af50b874006  # [osx and x86_64]
   
  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build_arm64 }}-jdk{{ version }}-macos_aarch64.zip  # [osx and arm64]
    sha256: 6f0461f2b2448ef7e5e0afe187364588312768bb77e737e90a20e8fc818394ed  # [osx and arm64]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-win_x64.zip  # [win64]
    sha256: b619df7a6f625095ee4adb3add44839b0b1af2adc09a16c7312ca96bb2b61ec9  # [win64]

  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip  # [linux]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a  # [linux]
    folder: fonts  # [linux]

  - url: https://hg.openjdk.java.net/jdk-updates/jdk{{ version.split(".")[0] }}u/archive/jdk-{{ version }}+{{ openjdk_revision }}.tar.bz2   # [linux]
    sha256: 1bfcf63e0be8fc37517856e6181b97ed1d83a2436949ad21855ffc6ce14a5a0e  # [linux]
    folder: src        # [linux]
    patches:           # [linux]
      - fix-arm.patch  # [linux]

build:
  number: 2

requirements:
  build:
    # We also need a compiler on osx to produce correct signatures
    - {{ compiler('cxx') }}   # [not win]
    - pkg-config        # [linux]
    - autoconf          # [linux]
    - unzip             # [linux]
    - zip               # [linux]
    - make !=4.3.*      # [linux]
    - zlib              # [linux and (build_platform != target_platform)]
    - freetype          # [linux and (build_platform != target_platform)]
    - harfbuzz          # [linux and (build_platform != target_platform)]
    - libpng            # [linux and (build_platform != target_platform)]
    - giflib            # [linux and (build_platform != target_platform)]
    - jpeg              # [linux and (build_platform != target_platform)]
    - libcups           # [linux and (build_platform != target_platform)]
    # - alsa-lib          # [linux and (build_platform != target_platform)]
    - fontconfig        # [linux and (build_platform != target_platform)]
    - xorg-libx11       # [linux and (build_platform != target_platform)]
    - xorg-libxext      # [linux and (build_platform != target_platform)]
    - xorg-libxt        # [linux and (build_platform != target_platform)]
    - xorg-libxtst      # [linux and (build_platform != target_platform)]
    - xorg-libxrender   # [linux and (build_platform != target_platform)]
    - xorg-libxrandr    # [linux and (build_platform != target_platform)]
    - xorg-libxi        # [linux and (build_platform != target_platform)]
    - lcms2             # [linux and (build_platform != target_platform)]
  host:
    - zlib              # [linux or osx]
    - freetype          # [linux]
    - harfbuzz          # [linux]
    - libpng            # [linux]
    - giflib            # [linux]
    - jpeg              # [linux]
    - libcups           # [linux]
    - alsa-lib          # [linux]
    - fontconfig        # [linux]
    - xorg-libx11       # [linux]
    - xorg-libxext      # [linux]
    - xorg-libxt        # [linux]
    - xorg-libxtst      # [linux]
    - xorg-libxrender   # [linux]
    - xorg-libxrandr    # [linux]
    - xorg-libxi        # [linux]
    - lcms2             # [linux]
    - vs2015_runtime    # [win]
  run:
    - xorg-libx11       # [linux]
    - xorg-libxext      # [linux]
    - xorg-libxtst      # [linux]
    - xorg-libxrender   # [linux]
    - xorg-libxi        # [linux]
    - {{ pin_compatible("alsa-lib", max_pin="x.x.x") }}     # [linux]
    - vs2015_runtime    # [win]

test:
  requires:
    - {{ compiler('c') }}  # [not win]
  files:
    - test-jni  # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh  # [not win]

about:
  home: https://www.azul.com/products/zulu/  # [not linux]
  home: https://openjdk.java.net             # [linux]
  license: GPL-2.0-or-later WITH Classpath-exception-2.0
  license_family: GPL
  license_file:
    - LICENSE
    - fonts/LICENSE   # [linux]
  summary: The Zulu OpenJDK build.           # [not linux]
  summary: An open-source implementation of the JDK   # [linux]
  description: Zulu OpenJDK is an open source build of the Java JDK.   # [not linux]

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - CJ-Wright
    - xhochy
