{% set version = "11.0.25" %}
{% set openjdk_revision = "9" %}
{% set zulu_build = "11.76.21-ca" %}

{% set major = version.split(".")[0] %}
{% set jdk_full = version ~ "+" ~ openjdk_revision %}

{% set temurin_url = "https://github.com/adoptium/temurin" ~ major ~ "-binaries/releases/download" %}
{% set temurin_base =  "jdk-" ~ jdk_full ~ "/OpenJDK" ~ major ~ "U-jdk" %}
{% set temurin_suffix = "linux_hotspot_" ~ jdk_full.replace("+", "_") ~ ".tar.gz" %}

{% set zulu_url = "https://cdn.azul.com/zulu/bin" %}
{% set zulu_base = "zulu" ~ zulu_build ~ "-jdk" ~ version %}

package:
  name: openjdk
  version: {{ version }}

source:
  # example of full url for version=11.0.21 & openjdk_revision=9:
  # https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21+9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.21_9.tar.gz
  - url: {{ temurin_url }}/{{ temurin_base }}_x64_{{ temurin_suffix }}        # [build_platform == "linux-64"]
    sha256: 191baa2e052627614022171400a917d28f0987dc54da48aaf07b06f552bb9884  # [build_platform == "linux-64"]
  # native compilation: currently unused
  - url: {{ temurin_url }}/{{ temurin_base }}_aarch64_{{ temurin_suffix }}    # [build_platform == "linux-aarch64"]
    sha256: 999fbd90b070f9896142f0eb28354abbeb367cbe49fd86885c626e2999189e0a  # [build_platform == "linux-aarch64"]
  - url: {{ temurin_url }}/{{ temurin_base }}_ppc64le_{{ temurin_suffix }}    # [build_platform == "linux-ppc64le"]
    sha256: a8fba686f6eb8ae1d1a9566821dbd5a85a1108b96ad857fdbac5c1e4649fc56f  # [build_platform == "linux-ppc64le"]

  - url: https://github.com/openjdk/jdk{{ major }}u/archive/refs/tags/jdk-{{ jdk_full }}.tar.gz                 # [linux]
    sha256: a669ef9e8e7b6ee58d3e5159df57fd12aa742819fbbe862f28b9dc749f47f04e  # [linux]
    folder: src                                                               # [linux]
    patches:                                                                  # [linux]
      - fix-arm.patch                                                         # [linux]
  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip  # [linux]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a  # [linux]
    folder: fonts                                                             # [linux]

  # example of full url for zulu_build=11.68.17-ca & version=11.0.21:
  # https://cdn.azul.com/zulu/bin/zulu11.68.17-ca-jdk11.0.21-macosx_x64.zip
  - url: {{ zulu_url }}/{{ zulu_base }}-macosx_x64.zip                        # [osx and x86_64]
    sha256: c138aa622095c17112b621825c110e7f0ef89a9b55b93ced701770bcc6a74998  # [osx and x86_64]
  - url: {{ zulu_url }}/{{ zulu_base }}-macosx_aarch64.zip                    # [osx and arm64]
    sha256: c156df27ddfe6b1b9287e20d74ef04d3350248fc04c590dc915a3c519222dd21  # [osx and arm64]
  - url: {{ zulu_url }}/{{ zulu_base }}-win_x64.zip                           # [win64]
    sha256: fd9dcce6d9f7e2929a94cd6655c4606b79f1686b56b4ac8413b396efe08f9139  # [win64]

build:
  number: 1
  # Binaries are already relocatable and conda-build's post-processing would add a very long RPATH to binaries
  # which doesn't fit anymore into the __LINKEDIT section. For this, we either need to manually reassemble
  # the Mach-O header or build everything from source.
  binary_relocation: false  # [osx]
  ignore_run_exports:
    # the produced artefacts still need libc++.*.dylib on osx,
    # but the one in the platform sdk is enough; avoid extra run-export
    - libcxx  # [osx]

requirements:
  build:
    # We also need a compiler on osx to produce correct signatures
    - {{ compiler('cxx') }}   # [not win]
    - {{ stdlib('c') }}       # [linux]
    - pkg-config        # [linux]
    - autoconf          # [linux]
    - unzip             # [linux]
    - zip               # [linux]
    - make              # [linux]
    - zlib              # [linux and (build_platform != target_platform)]
    - freetype          # [linux and (build_platform != target_platform)]
    - harfbuzz          # [linux and (build_platform != target_platform)]
    - libpng            # [linux and (build_platform != target_platform)]
    - giflib            # [linux and (build_platform != target_platform)]
    - libjpeg-turbo     # [linux and (build_platform != target_platform)]
    - libcups           # [linux and (build_platform != target_platform)]
    - alsa-lib          # [linux and (build_platform != target_platform)]
    - fontconfig        # [linux and (build_platform != target_platform)]
    - xorg-libx11       # [linux and (build_platform != target_platform)]
    - xorg-libxext      # [linux and (build_platform != target_platform)]
    - xorg-libxt        # [linux and (build_platform != target_platform)]
    - xorg-libxtst      # [linux and (build_platform != target_platform)]
    - xorg-libxrender   # [linux and (build_platform != target_platform)]
    - xorg-libxrandr    # [linux and (build_platform != target_platform)]
    - xorg-libxi        # [linux and (build_platform != target_platform)]
    - xorg-xorgproto    # [linux and (build_platform != target_platform)]
    - lcms2             # [linux and (build_platform != target_platform)]
    - symlink-exe-build  # [win]
    - m2-bash            # [win]
  host:
    - zlib              # [linux or osx]
    - freetype          # [linux]
    - harfbuzz          # [linux]
    - libpng            # [linux]
    - giflib            # [linux]
    - libjpeg-turbo     # [linux]
    - libcups           # [linux]
    - alsa-lib          # [linux]
    - fontconfig        # [linux]
    - xorg-libx11       # [linux]
    - xorg-libxext      # [linux]
    - xorg-libxt        # [linux]
    - xorg-libxtst      # [linux]
    - xorg-libxrender   # [linux]
    - xorg-libxrandr    # [linux]
    - xorg-libxi        # [linux]
    - xorg-xorgproto    # [linux]
    - lcms2             # [linux]
  run:
    - xorg-libx11       # [linux]
    - xorg-libxext      # [linux]
    - xorg-libxtst      # [linux]
    - xorg-libxrender   # [linux]
    - xorg-libxi        # [linux]

test:
  requires:
    - {{ compiler("cxx") }}  # [unix]
  files:
    - test-jni.sh
    - test-jni/
    - test-nio/
  commands:
    - java -version
    - '$JAVA_HOME/bin/java -version'    # [unix]
    - '%JAVA_HOME%\bin\java -version'   # [win]
    - ./test-jni.sh                     # [unix]

about:
  home: https://www.azul.com/products/zulu/  # [not linux]
  home: https://openjdk.java.net             # [linux]
  license: GPL-2.0-or-later WITH Classpath-exception-2.0
  license_family: GPL
  license_file:
    - LICENSE
    - fonts/LICENSE   # [linux]
  summary: The Zulu OpenJDK build.                    # [not linux]
  summary: An open-source implementation of the JDK   # [linux]
  description: Zulu OpenJDK is an open source build of the Java JDK.   # [not linux]

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - CJ-Wright
    - xhochy
    - izahn
