# Based on recipes from birdhouse and anaconda channel.

{% set name = "openjdk" %}
{% set version = "8.0.152" %}
{% set zulu_build = "8.25.0.1" %}
{% set build_number = 1 %}
{% set sha256_linux = "57911a136fedc476a8b505d00c364913bf4cf5b7a50ef6913334362bc219e21a" %}
{% set sha256_osx = "ea5797daeb74da7348c6725e2142359c6b34bcb97c142584ebeea07dc28db9c3" %}
{% set sha256_win = "f1d9d3341ef7c8c9baff3597953e99a6a7c64f8608ee62c03fdd7574b7655c02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_x64.tar.gz  # [linux64]
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-macosx_x64.zip    # [osx]
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-win_x64.zip       # [win64]
  sha256: {{ sha256_linux }}  # [linux64]
  sha256: {{ sha256_osx }}    # [osx]
  sha256: {{ sha256_win }}    # [win64]

build:
  number: {{ build_number }}
  skip: true  # [win32 or linux32]
  string: zulu{{ zulu_build }}_{{ build_number }}
  track_features:
    - openjdk

requirements:
  build:
    - curl


test:
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh                                # [not win]
    - conda inspect linkages -p ${PREFIX} openjdk  # [linux]
    - conda inspect objects -p ${PREFIX} openjdk   # [osx]

about:
  home: https://www.azul.com/products/zulu/
  license: GPLv2
  summary: The Zulu OpenJDK build.
  description: |
    Zulu OpenJDK is an open source build of the Java JDK.

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - abhi18av
