{% set name = "openjdk" %}
{% set version = "9.0.7" %}
{% set zulu_build = "9.0.7.1" %}
{% set build_number = 1012 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_x64.tar.gz  # [linux64]
    sha256: 45f2dfbee93b91b1468cf81d843fc6d9a47fef1f831c0b7ceff4f1eb6e6851c8  # [linux64]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-macosx_x64.zip  # [osx]
    sha256: 4b1f8529ff3a8bebc974e2a22395cb27ad8750e386c8c4d1b0a1b16f89cfcf66  # [osx]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-win_x64.zip  # [win64]
    sha256: 75f76c53c6a1f12b1a571b86bd9708ab75adf582d689dddc94fdd77dcc0f3f5c  # [win64]

  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip  # [linux64]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a  # [linux64]
    folder: fonts  # [linux64]

build:
  number: {{ build_number }}
  skip: true  # [win32 or linux32]
  string: c_compiler{{ c_compiler }}_{{ build_number }}  # [win64]

test:
  requires:
    - {{ compiler('c') }}  # [not win]
  files:
    - test-jni  # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh  # [not win]

about:
  home: https://www.azul.com/products/zulu/
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: The Zulu OpenJDK build.
  description: Zulu OpenJDK is an open source build of the Java JDK.

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - hadim
