{% set version = "22.0.1" %}
{% set openjdk_revision = "8" %}
{% set zulu_build = "22.30.13-ca" %}

{% set major = version.split(".")[0] %}
{% set jdk_full = version ~ "+" ~ openjdk_revision %}

{% set temurin_url = "https://github.com/adoptium/temurin" ~ major ~ "-binaries/releases/download" %}
{% set temurin_base =  "jdk-" ~ jdk_full ~ "/OpenJDK" ~ major ~ "U-jdk" %}
{% set temurin_suffix = "hotspot_" ~ jdk_full.replace("+", "_") ~ ".tar.gz" %}

{% set zulu_url = "https://cdn.azul.com/zulu/bin" %}
{% set zulu_base = "zulu" ~ zulu_build ~ "-jdk" ~ version %}

package:
  name: openjdk
  version: {{ version }}


source:
  # example of full url for version=17.0.8 & openjdk_revision=7:
  # https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.8+7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.8_7.tar.gz
  - url: {{ temurin_url }}/{{ temurin_base }}_x64_linux_{{ temurin_suffix }}  # [build_platform == "linux-64"]
    sha256: e59c6bf801cc023a1ea78eceb5e6756277f1564cd0a421ea984efe6cb96cfcf8  # [build_platform == "linux-64"]
  - url: {{ temurin_url }}/{{ temurin_base }}_x64_mac_{{ temurin_suffix }}    # [build_platform == "osx-64"]
    sha256: 9445952d4487451af024a9a3f56373df76fbd928d9ff9186988aa27be2e4f10c  # [build_platform == "osx-64"]

  - url: https://github.com/openjdk/jdk{{ major }}u/archive/refs/tags/jdk-{{ jdk_full }}.tar.gz                 # [unix]
    sha256: 0cfb7f2799384df43a9832df638f31c9be33a4a8650f8478f35272ee70dd7173  # [unix]
    folder: src                                                               # [unix]
  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip  # [unix]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a  # [unix]
    folder: fonts                                                             # [unix]

  # example of full url for zulu_build=17.44.15-ca & version=17.0.8:
  # https://cdn.azul.com/zulu/bin/zulu17.44.15-ca-jdk17.0.8-win_x64.zip
  - url: {{ zulu_url }}/{{ zulu_base }}-win_x64.zip                           # [win64]
    sha256: cf112b96b665eb34107590c83af83e56735caa677e2a96d1991419aa26b5d511  # [win64]

build:
  number: 1
  # debug
  skip: true  # [not osx]
  # Binaries are already relocatable and conda-build's post-processing would add a very long RPATH to binaries
  # which doesn't fit anymore into the __LINKEDIT section. For this, we either need to manually reassemble
  # the Mach-O header or build everything from source.
  binary_relocation: false  # [osx]
  ignore_run_exports:
    # the produced artefacts still need libc++.*.dylib on osx,
    # but the one in the platform sdk is enough; avoid extra run-export
    - libcxx  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}   # [unix]
    - {{ stdlib('c') }}       # [unix]
    - cctools_osx-64          # [osx and (build_platform != target_platform)]
    - libcxx                  # [osx and (build_platform != target_platform)]
    - pkg-config        # [unix]
    - autoconf          # [unix]
    - unzip             # [unix]
    - zip               # [unix]
    - make !=4.3.*      # [unix]
    - zlib              # [unix and (build_platform != target_platform)]
    - freetype          # [unix and (build_platform != target_platform)]
    - harfbuzz          # [unix and (build_platform != target_platform)]
    - libpng            # [unix and (build_platform != target_platform)]
    - giflib            # [unix and (build_platform != target_platform)]
    - libiconv          # [osx and (build_platform != target_platform)]
    - libjpeg-turbo     # [unix and (build_platform != target_platform)]
    - libcups           # [linux and (build_platform != target_platform)]
    - alsa-lib          # [linux and (build_platform != target_platform)]
    - fontconfig        # [unix and (build_platform != target_platform)]
    - xorg-libx11       # [unix and (build_platform != target_platform)]
    - xorg-libxext      # [unix and (build_platform != target_platform)]
    - xorg-libxt        # [unix and (build_platform != target_platform)]
    - xorg-libxtst      # [unix and (build_platform != target_platform)]
    - xorg-libxrender   # [unix and (build_platform != target_platform)]
    - xorg-libxrandr    # [unix and (build_platform != target_platform)]
    - xorg-libxi        # [unix and (build_platform != target_platform)]
    - lcms2             # [unix and (build_platform != target_platform)]
    - symlink-exe-build  # [win]
    - m2-bash            # [win]
  host:
    - zlib              # [unix]
    - freetype          # [unix]
    - harfbuzz          # [unix]
    - libpng            # [unix]
    - giflib            # [unix]
    - libiconv          # [osx]
    - libjpeg-turbo     # [unix]
    - libcups           # [linux]
    - alsa-lib          # [linux]
    - fontconfig        # [unix]
    - xorg-libx11       # [unix]
    - xorg-libxext      # [unix]
    - xorg-libxt        # [unix]
    - xorg-libxtst      # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libxrandr    # [unix]
    - xorg-libxi        # [unix]
    - lcms2             # [unix]
    - vc14_runtime      # [win]
  run:
    - vc14_runtime      # [win]

test:
  requires:
    - {{ compiler('c') }}  # [not win]
  files:
    - test-jni  # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - '${JAVA_HOME}/bin/java -version'  # [not win]
    - '%JAVA_HOME%\bin\java -version'   # [win]
    - ./test-jni.sh  # [not win and not ppc64le]
    - test -f ${JAVA_HOME}/release              # [not win]
    - if not exist %JAVA_HOME%\\release exit 1  # [win]

about:
  home: https://www.azul.com/products/zulu/  # [win]
  home: https://openjdk.java.net             # [unix]
  license: GPL-2.0-or-later WITH Classpath-exception-2.0
  license_family: GPL
  license_file:
    - LICENSE
    - fonts/LICENSE   # [unix]
  summary: An open-source implementation of the JDK                     # [unix]
  summary: The Zulu OpenJDK build.                                      # [win]
  description: Zulu OpenJDK is an open source build of the Java JDK.    # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - CJ-Wright
    - xhochy
    - izahn
    - h-vetinari
