# Based on recipes from birdhouse and anaconda channel.

{% set name = "openjdk" %}
{% set version = "7.0.161" %}
{% set zulu_build = "7.21.0.3" %}
{% set build_number = 0 %}
{% set sha256_linux = "af1ea1676d33ec655a1d333709829b9242d55f7ec7de21e6295a2a2ad7dd43a5" %}
{% set sha256_osx = "6bb3d562b79e97c08e33f5eaf3a0193a1b8b0617105a3fbdcfe833d04bdbe2fd" %}
{% set sha256_win = "73a9e326a30cf53388de447c1ec8552744b24d4822ad57634615232fd27b3f55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_x64.tar.gz  # [linux64]
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-macosx_x64.zip    # [osx]
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-win_x64.zip       # [win64]
  sha256: {{ sha256_linux }}  # [linux64]
  sha256: {{ sha256_osx }}    # [osx]
  sha256: {{ sha256_win }}    # [win64]

build:
  number: {{ build_number }}
  skip: true  # [win32 or linux32]
  string: zulu{{ zulu_build }}_{{ build_number }}
  track_features:
    - openjdk

requirements:
  build:
    - curl


test:
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh                                # [not win]
    - conda inspect linkages -p ${PREFIX} openjdk  # [linux]
    - conda inspect objects -p ${PREFIX} openjdk   # [osx]

about:
  home: https://www.azul.com/products/zulu/
  license: GPLv2
  summary: The Zulu OpenJDK build.
  description: |
    Zulu OpenJDK is an open source build of the Java JDK.

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
