travis:
  secure:
    BINSTAR_TOKEN: mZOdzaUQcwut51vWlnTmEWWwUEwNZBVVZlD9J/hjcOvyzvg50L1+gQamENJYYLOuP5lbvN0lDp5WsYN3eUwNSVVehG3X9alxVVhUhPuzxJODJ93c+43q9nGFCkp+6vcYa3322rIhXjPVW0+nFrOHy3HhLRGtLcg4i6tz0zTSjqB2/SoZMzcs2uTlVyYzBUFOIInbPPIFwRwgEHoHFjWwM6iVRk+B/McA48SGSXHI//yH5sEqD0JrPRShdlZFccjKT2aOtbeMeobgxgYEDmGB5ni08G85lm79CREKANRBlXUsgPA0cE8dWtyPDoqTVNVHnTO0T0DF8oBeKG+jcDQ8r6n2ZIxSp/KquZd4074V/FLFIbQQW/Nnt3YZv5RbbOqgKH9U+bN1Z+yQX0Utho63TyEG80365CIHWZ8fuNnug7IOAq5Pebo04Zhi9jK4iNJhMYV9+iGKRge53PysvNBUjnMBVzrkJlQM8/IsBu4UEoLCVvLfOh0BHKzRRdNAfk2RhQ/yEke9EJfdYuh0pyCHt6QRNOgaV0Oob2YLN9CcCjmECHQX8+EzUGeZ5yhQhCOBlj1NVaU5s3MXDwaK0WuLPaHr7Lyv0x9r6tpCE9hSleG5TDdg1LNxABaOlf9R3Eg43kM6a+DU8Z20RVI4KZCDPXSbA0lliKLYYDGI/xRULxI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
provider:
  linux_ppc64le: default
  linux_aarch64: default
